name: practical_work

channels:
  - pytorch
  - nvidia

dependencies:
  - pip
  - python=3.9.7
  - pytorch=1.10.1
  - numpy==1.21.2
  - pandas==1.3.5
  - cudatoolkit==11.3.1
  - torchvision
  - matplotlib
  - pandas
